services:
  # backend:
  #   container_name: backend
  #   build:
  #     context: ./src/backend
  #     dockerfile: dockerfile
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./src/backend/.env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - cns_network

  db:
    container_name: mysqldb
    build:
      context: ./src/mysqldb
      dockerfile: dockerfile
    platform: linux/amd64
    stdin_open: true
    tty: true
    restart: always
    working_dir: /var/lib/mysql
    command: --bind-address=0.0.0.0
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - 3307:3306
    volumes:
      - CNS_DB:/var/lib/mysql
      #- ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "CNS_DB"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} && mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e 'show databases;'",
        ]
      timeout: 25s
      retries: 10
    networks:
      - cns_network

volumes:
  CNS_DB:

networks:
  cns_network:
